name: Weekly Accomplishments Run

on: 
  schedule:
    - cron: '0 20 * * 5'
  
  workflow_dispatch:

jobs:
  run-weekly-accomplishments:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - run: git config user.name 'github-actions[bot]'
      - run: git config user.email 'github-actions[bot]@users.noreply.github.com'

      - run: |
          if [ !-z $(grep "enable_accomplishments=true" "config.ini") ]; then
            echo 'Accomplishment automations are disabled!'
            
            exit 1
          fi

      - run: echo "# Accomplishments for Week ending at $(date +'%Y-%m-%d')" >  "./accomplishments/$(date +'%Y-%m-%d').md"
      - run: echo "" >>  "./accomplishments/$(date +'%Y-%m-%d').md"
      - run: echo "- [ ] Started recording my accomplishments for the week" >>  "./accomplishments/$(date +'%Y-%m-%d').md"
      
      - run: git add .
      - run: "git commit --allow-empty -m 'chore: add new weekly accomplishments file'"
      
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ github.ref }}
          github_token: ${{ github.token }}
          tags: true

      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{secrets.MAIL_HOST}}
          server_port: ${{secrets.MAIL_PORT}}
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: It's time to track your weekly accomplishments!
          to: ${{secrets.TO_ADDRESS}}
          from: ${{secrets.FROM_ADDRESS}}
          secure: true
          body: It's time to track your weekly accomplishments
          html_body: file://.templates/weekly-accomplishments.html
          ignore_cert: true